name: Deploy subgraph

on:
  push:
    branches: [master, 'develop/**']

jobs:
  deploy:
    strategy:
      matrix:
        node: ["12.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn

      - run: yarn

      - run: | 
          yarn prepare-subgraph:mainnet
          yarn prepare-constants:mainnet
          yarn codegen
          yarn build
          yarn deploy-thegraph-mainnet --access-token ${{ secrets.ACCESS_TOKEN_MAINNET }}
        if: github.ref == 'refs/heads/master'

      - run: |
          yarn prepare:ropsten
          yarn codegen
          yarn build
          yarn deploy-thegraph-ropsten --access-token ${{ secrets.ACCESS_TOKEN_ROPSTEN }}
        if: startsWith(github.ref, 'refs/heads/develop')
