name: Deploy subgraph

on:
  push:
    branches: [master, 'develop/ropsten/**', 'develop/bsc/**', 'develop/polygon/**', 'develop/arbitrum/**']

jobs:
  deploy:
    strategy:
      matrix:
        node: ["12.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn

      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - run: yarn

      - run: | 
          yarn prepare:mainnet
          yarn codegen
          yarn build
          yarn deploy-thegraph-mainnet --access-token ${{ secrets.ACCESS_TOKEN_MAINNET }}
        if: github.ref == 'refs/heads/master'

      - run: |
          yarn prepare:ropsten
          yarn codegen
          yarn build
          yarn deploy-thegraph-ropsten --access-token ${{ secrets.ACCESS_TOKEN_ROPSTEN }}
        if: startsWith(github.ref, 'refs/heads/develop/ropsten')

      - run: |
          yarn prepare:bsc
          yarn codegen
          yarn build
          yarn deploy-thegraph-bsc --access-token ${{ secrets.ACCESS_TOKEN_MAINNET }}
        if: startsWith(github.ref, 'refs/heads/develop/bsc')        

      - run: |
          yarn prepare:polygon
          yarn codegen
          yarn build
          yarn deploy-thegraph-polygon --access-token ${{ secrets.ACCESS_TOKEN_MAINNET }}
        if: startsWith(github.ref, 'refs/heads/develop/polygon')          

      - run: |
          yarn prepare:arbitrum
          yarn codegen
          yarn build
          yarn deploy-thegraph-arbitrum --access-token ${{ secrets.ACCESS_TOKEN_MAINNET }}
        if: startsWith(github.ref, 'refs/heads/develop/arbitrum')                
